image: python:3.11-slim
stages:
  - test
  - deploy

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

cache:
  key:
    files:
      - pyproject.toml
      - requirements.txt
  paths:
    - "$UV_CACHE_DIR"

before_script:
  - apt-get update && apt-get install -y build-essential git
  - pip install uv

test:
  stage: test
  script:
    - uv venv
    - uv run  --with pytest,pytest-asyncio pytest
  except:
    - tags

publish:
  stage: deploy
  script:
    - uv venv
    - uv build --wheel
    - UV_PUBLISH_PASSWORD=${CI_JOB_TOKEN} UV_PUBLISH_USERNAME=gitlab-ci-token uv publish --publish-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  only:
    - tags
