FROM python:3.12-slim AS builder

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    python3-dev \
    ca-certificates \
    git \
    patchelf \
    && rm -rf /var/lib/apt/lists/*

RUN pip install Nuitka

WORKDIR /build

COPY pyproject.toml setup.py README.md ./
COPY src/ ./src/

RUN pip install -e .
RUN mkdir dist
RUN nuitka --mode=onefile --output-filename=dist/ofx src/ofx

FROM scratch AS export
COPY --from=builder /build/dist/ofx /ofx
