[project]
name = "ofx"
version = "0.1.0"
description = "Offensive Flow Executor tool for handing over to the next generation of red teamers"
readme = "README.md"
authors = [
    { name = "anhhung04", email = "dev.hah4@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "async-typer>=0.1.9",
    "filelock>=3.18.0",
    "gitpython>=3.1.45",
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pydantic-settings-yaml>=0.2.0",
    "typer>=0.16.0",
]

[project.scripts]
ofx = "ofx:main"

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"
