.TH OFX 1 "January 2026" "OFX 0.3.2"
.SH NAME
ofx \- Offensive Flow Executor for Red Team Operations
.SH SYNOPSIS
.B ofx
[\fIOPTIONS\fR] \fICOMMAND\fR [\fIARGS\fR]...
.SH DESCRIPTION
.B ofx
is a comprehensive toolkit for red team operations including exploitation,
post-exploitation, enumeration utilities, and webshell management.
.PP
OFX provides a unified interface for various offensive security tools and
automation workflows.
.SH OPTIONS
.TP
.B \-\-help
Show help message and exit.
.TP
.B \-\-version
Show version number and exit.
.SH COMMANDS
Use
.B ofx \-\-help
to see all available commands.
.SH FILES
.TP
.I /usr/share/ofx/
Data files and templates.
.TP
.I ~/.config/ofx/
User configuration directory.
.SH AUTHOR
OFX Developer <dev.hah4@gmail.com>
.SH SEE ALSO
.BR ssh (1),
.BR scp (1)
.SH COPYRIGHT
Copyright \(co 2024-2026 OFX Developer.
Licensed under the MIT License.
