"""Build self-contained shell scripts from workflow jobs for detached execution.

The generated script includes all steps, environment setup, timestamped logging,
and status markers (__OFX_DONE__ / __OFX_FAIL__) so the session manager can
detect completion by tailing the log file.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from ofx.models.step import RunType, Step


def build_session_script(
    steps: list[Step],
    *,
    session_id: str,
    work_dir: str,
    env: dict[str, str] | None = None,
    os_type: str = "linux",
) -> str:
    """Generate a self-contained script that runs all steps in sequence.

    Args:
        steps: Job steps to include.
        session_id: Session identifier (embedded in markers).
        work_dir: Remote/local working directory.
        env: Extra environment variables to export.
        os_type: "linux" (bash) or "windows" (powershell).

    Returns:
        Script content as a string.
    """
    if os_type == "windows":
        return _build_powershell(steps, session_id, work_dir, env or {})
    return _build_bash(steps, session_id, work_dir, env or {})


# ------------------------------------------------------------------
# Bash (Linux)
# ------------------------------------------------------------------


def _build_bash(
    steps: list[Step],
    session_id: str,
    work_dir: str,
    env: dict[str, str],
) -> str:
    lines: list[str] = [
        "#!/bin/bash",
        "# Auto-generated by OFX session manager",
        f'export OFX_SESSION_ID="{session_id}"',
        f'WORK_DIR="{work_dir}"',
        'LOG_FILE="$WORK_DIR/output.log"',
        'mkdir -p "$WORK_DIR/output"',
        'cd "$WORK_DIR"',
        "",
    ]

    # Environment variables
    for key, value in env.items():
        if key in ("PATH", "HOME", "USER", "SHELL"):
            continue
        lines.append(f'export {key}="{_bash_escape(str(value))}"')
    if env:
        lines.append("")

    # Logging helper
    lines.extend([
        '_log() { echo "[$(date +%Y-%m-%dT%H:%M:%S)] $*" >> "$LOG_FILE"; }',
        '_log "Session $OFX_SESSION_ID started"',
        "",
    ])

    # Each step wrapped with error handling
    for idx, step in enumerate(steps):
        step_name = step.name or f"step_{idx}"
        lines.append(f'_log ">>> Step {idx}: {step_name}"')

        cmd = _step_command_bash(step, work_dir)
        if step.continue_on_error:
            lines.append(f'({cmd}) >> "$LOG_FILE" 2>&1 || _log "Step {idx} failed (continue_on_error)"')
        else:
            lines.extend([
                f'({cmd}) >> "$LOG_FILE" 2>&1',
                "STEP_RC=$?",
                'if [ $STEP_RC -ne 0 ]; then',
                f'  _log "Step {idx} FAILED (exit $STEP_RC)"',
                '  _log "__OFX_FAIL__"',
                "  exit $STEP_RC",
                "fi",
            ])
        lines.append(f'_log "<<< Step {idx} done"')
        lines.append("")

    lines.extend([
        '_log "All steps completed successfully"',
        '_log "__OFX_DONE__"',
    ])

    return "\n".join(lines) + "\n"


def _step_command_bash(step: Step, work_dir: str) -> str:
    """Extract the shell command(s) from a step for bash."""
    run_type = step.get_run_type()
    # Always use session work_dir — step.working_directory defaults to CWD
    # which is meaningless for detached session scripts.
    cwd = work_dir

    if run_type == RunType.COMMAND:
        return f"cd {cwd} 2>/dev/null; {step.run}"

    if run_type == RunType.SCRIPT:
        # Inline script — run via heredoc
        escaped = step.script.replace("'", "'\\''")
        return f"cd {cwd} 2>/dev/null; bash -c '{escaped}'"

    if run_type == RunType.SCRIPT_FILE:
        return f"cd {cwd} 2>/dev/null; bash {step.script_file}"

    return f'echo "Unsupported run type: {run_type}"'


def _bash_escape(s: str) -> str:
    """Escape double-quotes and backslashes for bash."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")


# ------------------------------------------------------------------
# PowerShell (Windows)
# ------------------------------------------------------------------


def _build_powershell(
    steps: list[Step],
    session_id: str,
    work_dir: str,
    env: dict[str, str],
) -> str:
    lines: list[str] = [
        "# Auto-generated by OFX session manager",
        "$ErrorActionPreference = 'Stop'",
        f'$env:OFX_SESSION_ID = "{session_id}"',
        f'$WORK_DIR = "{work_dir}"',
        '$LOG_FILE = "$WORK_DIR\\output.log"',
        'New-Item -ItemType Directory -Force -Path "$WORK_DIR\\output" | Out-Null',
        'Set-Location $WORK_DIR',
        "",
    ]

    # Environment variables
    for key, value in env.items():
        if key in ("PATH", "HOME", "USER", "SHELL"):
            continue
        lines.append(f'$env:{key} = "{value}"')
    if env:
        lines.append("")

    # Log helper
    lines.extend([
        'function Write-Log($msg) { "[$((Get-Date).ToString(\"yyyy-MM-ddTHH:mm:ss\"))] $msg" | Out-File -Append -FilePath $LOG_FILE }',
        'Write-Log "Session $env:OFX_SESSION_ID started"',
        "",
    ])

    for idx, step in enumerate(steps):
        step_name = step.name or f"step_{idx}"
        lines.append(f'Write-Log ">>> Step {idx}: {step_name}"')
        lines.append("try {")

        cmd = _step_command_ps(step, work_dir)
        lines.append(f"  {cmd} *>> $LOG_FILE")

        if step.continue_on_error:
            lines.append("} catch {")
            lines.append(f'  Write-Log "Step {idx} failed (continue_on_error): $_"')
            lines.append("}")
        else:
            lines.append("} catch {")
            lines.append(f'  Write-Log "Step {idx} FAILED: $_"')
            lines.append('  Write-Log "__OFX_FAIL__"')
            lines.append("  exit 1")
            lines.append("}")

        lines.append(f'Write-Log "<<< Step {idx} done"')
        lines.append("")

    lines.extend([
        'Write-Log "All steps completed successfully"',
        'Write-Log "__OFX_DONE__"',
    ])

    return "\n".join(lines) + "\n"


def _step_command_ps(step: Step, work_dir: str) -> str:
    """Extract PowerShell command from a step."""
    run_type = step.get_run_type()
    # Always use session work_dir — step.working_directory defaults to CWD
    cwd = work_dir

    if run_type == RunType.COMMAND:
        return f'Set-Location "{cwd}"; {step.run}'

    if run_type == RunType.SCRIPT:
        escaped = step.script.replace('"', '`"')
        return f'Set-Location "{cwd}"; Invoke-Expression "{escaped}"'

    if run_type == RunType.SCRIPT_FILE:
        return f'Set-Location "{cwd}"; & "{step.script_file}"'

    return f'Write-Output "Unsupported run type: {run_type}"'
