name: Test and Build

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install uv
        uses: https://github.com/astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: |
          uv run --extra test pytest tests/ -v --tb=short
